In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# ============================================================
# PATHS
# ============================================================

PROCESSED_DIR = Path("../data/processed")
OUTPUT_DIR = Path("../data/final")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

DEDUP_PATH = PROCESSED_DIR / "deduplicated_sample.parquet"
CANONICAL_PATH = PROCESSED_DIR / "canonical_entities_full_sample.parquet"

print(OUTPUT_DIR)

..\data\final

In [3]:
# ============================================================
# LOAD FINAL ARTIFACTS
# ============================================================

deduplicated = pd.read_parquet(DEDUP_PATH)
canonical_entities = pd.read_parquet(CANONICAL_PATH)

print(f"Deduplicated rows: {len(deduplicated):,}")
print(f"Canonical entities: {len(canonical_entities):,}")

Deduplicated rows: 89,133
Canonical entities: 75,690

In [4]:
# ============================================================
# BUILD CUSTOMER-FACING DEDUPLICATED FILE
# ============================================================

deduplicated_export_cols = [
    "record_id",
    "country",
    "source_snapshot_date",
    "relation_kind",
    "relation_role",
    "party_type",
    "company_public_id",
    "company_name_norm",
    "party_public_id",
    "party_name",
    "name_latin",
    "entity_id",
    "cluster_size",
    "canonical_name",
]

deduplicated_export_cols = [
    col for col in deduplicated_export_cols
    if col in deduplicated.columns
]

deduplicated_export = deduplicated[
    deduplicated_export_cols
].copy()

display(deduplicated_export.head())

print(f"Rows: {len(deduplicated_export):,}")
print(f"Columns: {len(deduplicated_export.columns)}")

,record_id,country,source_snapshot_date,relation_kind,relation_role,party_type,company_public_id,company_name_norm,party_public_id,party_name,name_latin,entity_id,cluster_size,canonical_name
0,mng_rec_3604c8299570c9b81987c24172904fce,mng,2026-01-11,director,Гүйцэтгэх захирал,individual,mng_company_51dea68295da4181,эрэнгүүн,NaN,Уламбаяр Мөнхбаяр,ulambayar monhbayar,single_2621448,1,ulambayar monhbayar
1,mng_rec_098d98e586d451875fa8583139040706,mng,2026-01-11,shareholder,shareholder,individual,mng_company_ac78bca957551275,ашид ундран аривжих,NaN,сүхбаатар оюунэрдэнэ,suhbaatar oyuunerdene,entity_00004174,3,suhbaatar oyuunerdene
2,kgz_rec_cea45e458fc1c18065819b25cb2c96ca,kgz,2022-02-15,shareholder,founder,unknown,kgz_company_b544fdf3f9c3f4f9,нукура алтын кол кол өнөрчүлүк өндүрүштүк комм...,NaN,Курманбекова Рахат Сапарбаевна,kurmanbekova rahat saparbaevna,single_2097162,1,kurmanbekova rahat saparbaevna
3,kaz_rec_b2a7bdd43eb32a7b30b214ab5b675c59,kaz,2024-11-04,director,director,individual,kaz_company_5f5f68be2d903187,qaznamys жауапкершілігі шектеулі серіктестігі,NaN,БАЯХМЕТОВА САЛТАНАТ МУРАТОВНА,bayahmetova saltanat muratovna,single_1048589,1,bayahmetova saltanat muratovna
4,arm_rec_902a34f25303eab1e1b4693858ace39c,arm,2025-02-05,shareholder,beneficial_owner,individual,arm_company_0e7508964355da0e,ավտոտրանսպորտային միջոցների հետազոտական կենտրոն,NaN,Լևոն Պետրոսյան,leuon petrosyan,entity_00002706,2,leuon petrosyan

Rows: 89,133
Columns: 14

In [5]:
# ============================================================
# BUILD CUSTOMER-FACING CANONICAL ENTITIES FILE
# ============================================================

canonical_export_cols = [
    "entity_id",
    "canonical_name",
    "cluster_size",
    "canonical_country",
    "canonical_script",
    "main_relation_kind",
    "main_relation_role",
    "unique_names_count",
    "unique_countries_count",
    "unique_companies_count",
    "is_singleton",
    "is_large_cluster",
    "is_suspicious_entity",
    "original_names",
    "normalized_names",
    "countries",
    "companies",
    "record_ids",
]

canonical_export_cols = [
    col for col in canonical_export_cols
    if col in canonical_entities.columns
]

canonical_export = canonical_entities[
    canonical_export_cols
].copy()

display(canonical_export.head())

print(f"Rows: {len(canonical_export):,}")
print(f"Columns: {len(canonical_export.columns)}")

,entity_id,canonical_name,cluster_size,canonical_country,canonical_script,main_relation_kind,main_relation_role,unique_names_count,unique_countries_count,unique_companies_count,is_singleton,is_large_cluster,is_suspicious_entity,original_names,normalized_names,countries,companies,record_ids
0,entity_00003316,neo metals holding limited,369,arm,armenian,shareholder,beneficial_owner,1,1,3,0,1,0,[ՆԵՈ ՄԵՏԱԼՍ ՀՈԼԴԻՆԳ ԼԻՄԻԹԵԴ],[neo metals holding limited],[arm],"[arm_company_4ac77af48cd1504b, arm_company_d2d...","[arm_rec_3022a3a56540d48694271518222308d3, arm..."
1,entity_00004228,svetlana ershova,274,arm,armenian,shareholder,beneficial_owner,1,1,3,0,1,0,[Սվետլանա Երշովա],[svetlana ershova],[arm],"[arm_company_5e54f57bb6578fa0, arm_company_447...","[arm_rec_11503193d53e75fb58c1e131a1089044, arm..."
2,entity_00003091,mirzaaziz mousakhanov,274,arm,armenian,shareholder,beneficial_owner,1,1,1,0,1,0,[Միրզաազիզ Մուսախանով],[mirzaaziz mousakhanov],[arm],[arm_company_9ea012e52301bdba],"[arm_rec_d114d4feb3678d20cf5a8142e3d9d8ae, arm..."
3,entity_00000439,ardyounaberakan ynkeroutyoun by,230,arm,armenian,shareholder,beneficial_owner,1,1,5,0,1,0,[ԱՐԴՅՈՒՆԱԲԵՐԱԿԱՆ ԸՆԿԵՐՈՒԹՅՈՒՆ ԲԸ],[ardyounaberakan ynkeroutyoun by],[arm],"[arm_company_4395cf02aed950d7, arm_company_9aa...","[arm_rec_26ce9d3b62b84449d1aa3030a09fa794, arm..."
4,entity_00003585,promishlennaya kompania,173,arm,armenian,shareholder,beneficial_owner,1,1,5,0,1,0,"[ՊՐՈՄԻՇԼԵՆՆԱՅԱ ԿՈՄՊԱՆԻԱ, Պրոմիշլեննայա կոմպանիա]",[promishlennaya kompania],[arm],"[arm_company_4fff645568ba424d, arm_company_9aa...","[arm_rec_8e868875dab2c569ddf4482052e0ddd1, arm..."

Rows: 75,690
Columns: 18

In [6]:
# ============================================================
# CLUSTER DISTRIBUTION REPORT
# ============================================================

cluster_distribution = (
    canonical_export
    .groupby("cluster_size")
    .size()
    .reset_index(name="entities_count")
    .sort_values("cluster_size")
)

display(cluster_distribution.head(30))

print("Largest clusters:")
display(
    canonical_export
    .sort_values("cluster_size", ascending=False)
    .head(20)
)

    cluster_size  entities_count
0              1           69737
1              2            4235
2              3             819
3              4             319
4              5             188
5              6              85
6              7              75
7              8              43
8              9              33
9             10              20
10            11              16
11            12              13
12            13              15
13            14               7
14            15               6
15            16               7
16            17              11
17            18               4
18            19               3
19            20               1
20            21               3
21            22               3
22            23               4
23            24               1
24            25               4
25            26               1
26            27               1
27            28               1
28            29               1
29            30               1

Largest clusters:

,entity_id,canonical_name,cluster_size,canonical_country,canonical_script,main_relation_kind,main_relation_role,unique_names_count,unique_countries_count,unique_companies_count,is_singleton,is_large_cluster,is_suspicious_entity,original_names,normalized_names,countries,companies,record_ids
0,entity_00003316,neo metals holding limited,369,arm,armenian,shareholder,beneficial_owner,1,1,3,0,1,0,[ՆԵՈ ՄԵՏԱԼՍ ՀՈԼԴԻՆԳ ԼԻՄԻԹԵԴ],[neo metals holding limited],[arm],"[arm_company_4ac77af48cd1504b, arm_company_d2d...","[arm_rec_3022a3a56540d48694271518222308d3, arm..."
1,entity_00004228,svetlana ershova,274,arm,armenian,shareholder,beneficial_owner,1,1,3,0,1,0,[Սվետլանա Երշովա],[svetlana ershova],[arm],"[arm_company_5e54f57bb6578fa0, arm_company_447...","[arm_rec_11503193d53e75fb58c1e131a1089044, arm..."
2,entity_00003091,mirzaaziz mousakhanov,274,arm,armenian,shareholder,beneficial_owner,1,1,1,0,1,0,[Միրզաազիզ Մուսախանով],[mirzaaziz mousakhanov],[arm],[arm_company_9ea012e52301bdba],"[arm_rec_d114d4feb3678d20cf5a8142e3d9d8ae, arm..."
3,entity_00000439,ardyounaberakan ynkeroutyoun by,230,arm,armenian,shareholder,beneficial_owner,1,1,5,0,1,0,[ԱՐԴՅՈՒՆԱԲԵՐԱԿԱՆ ԸՆԿԵՐՈՒԹՅՈՒՆ ԲԸ],[ardyounaberakan ynkeroutyoun by],[arm],"[arm_company_4395cf02aed950d7, arm_company_9aa...","[arm_rec_26ce9d3b62b84449d1aa3030a09fa794, arm..."
4,entity_00003585,promishlennaya kompania,173,arm,armenian,shareholder,beneficial_owner,1,1,5,0,1,0,"[ՊՐՈՄԻՇԼԵՆՆԱՅԱ ԿՈՄՊԱՆԻԱ, Պրոմիշլեննայա կոմպանիա]",[promishlennaya kompania],[arm],"[arm_company_4fff645568ba424d, arm_company_9aa...","[arm_rec_8e868875dab2c569ddf4482052e0ddd1, arm..."
5,entity_00003314,neo metals holding limited bazhnetomserov sahm...,104,arm,armenian,shareholder,beneficial_owner,1,1,2,0,1,0,[ՆԵՈ ՄԵՏԱԼՍ ՀՈԼԴԻՆԳ ԼԻՄԻԹԵԴ բաժնետոմսերով սահմ...,[neo metals holding limited bazhnetomserov sah...,[arm],"[arm_company_eebb72b6350c7510, arm_company_907...","[arm_rec_0962defc94da8756fe827163ba67cb83, arm..."
6,entity_00002356,irina gorshkova,81,arm,armenian,shareholder,beneficial_owner,1,1,0,0,1,0,[Իրինա Գորշկովա],[irina gorshkova],[arm],[],"[arm_rec_f628831964174b9caae2f60a05d433a2, arm..."
7,entity_00001791,fayrbyrd menejment spy,76,arm,armenian,shareholder,beneficial_owner,1,1,1,0,1,0,[ՖԱՅՐԲԸՐԴ ՄԵՆԵՋՄԵՆՏ ՍՊԸ],[fayrbyrd menejment spy],[arm],[arm_company_384750200fe9802a],"[arm_rec_8a704451fb86621c9f26cfe66f4034d2, arm..."
8,entity_00004152,star dast pby,74,arm,armenian,shareholder,beneficial_owner,1,1,3,0,1,0,[«ՍԹԱՐ ԴԱՍԹ» ՓԲԸ],[star dast pby],[arm],"[arm_company_9aa93e9d5e21b0ba, arm_company_871...","[arm_rec_d7c1382b7cf76d1d418684149142976d, arm..."
9,entity_00001783,evgenia vasileva,71,arm,armenian,shareholder,beneficial_owner,1,1,0,0,1,0,[Եվգենիա Վասիլեվա],[evgenia vasileva],[arm],[],"[arm_rec_0c8432d29b7f9dc2ca6642cb23af6df6, arm..."
10,entity_00004676,vahik zakharyants,68,arm,armenian,shareholder,beneficial_owner,1,1,20,0,1,0,"[ՎԱՀԻԿ ԶԱԽԱՐՅԱՆՑ, Վահիկ Զախարյանց]",[vahik zakharyants],[arm],"[arm_company_001ba7fb4ee213df, arm_company_ca3...","[arm_rec_ab60e6f8665228fa785e1583176e3b25, arm..."
11,entity_00000148,aleqsandr trounov,67,arm,armenian,shareholder,beneficial_owner,1,1,0,0,1,0,[Ալեքսանդր Տրունով],[aleqsandr trounov],[arm],[],"[arm_rec_50812eb29acb97cabfdc5f5f01593e6c, arm..."
12,entity_00003065,ministerstvo obrazovaniya i nauki kyrgyzskoi r...,65,kgz,cyrillic,shareholder,founder,2,1,64,0,1,0,[Министерство образования и науки Кыргызской Р...,[ministerstvo obrazovaniya i nauki kyrgyzskoi ...,[kgz],"[kgz_company_b10e45fc7a96037a, kgz_company_aa9...","[kgz_rec_07257edc9443ace2213c3832d93975ca, kgz..."
13,entity_00003861,samvel karapetyan,55,arm,armenian,shareholder,beneficial_owner,1,1,21,0,1,0,"[Սամվել Կարապետյան, Սամվել Կարապետյան]",[samvel karapetyan],[arm],"[arm_company_e9292f1ef005020b, arm_company_a0a...","[arm_rec_c03398238d6b037b2cf460cb266e8863, arm..."
14,entity_00001974,geuorg nalbandyan,54,arm,armenian,shareholder,beneficial_owner,2,1,18,0,1,0,"[Գևորգ Նալբանդյան, Գևորգ Նալվանդյան]","[geuorg nalbandyan, geuorg nalvandyan]",[arm],"[arm_company_7df3aed5eae772cc, arm_company_4e4...","[arm_rec_5356c151618d1757b83bcb9df547e7a6, arm..."
15,entity_00002002,gleb trotsenko,48,arm,armenian,shareholder,beneficial_owner,1,1,2,0,1,0,[Գլեբ Տրոցենկո],[gleb trotsenko],[arm],"[arm_company_9ea012e52301bdba, arm_company_841...","[arm_rec_9d977288911d3099a0ce12779784dd4a, arm..."
16,entity_00003914,sasoun avetisyan,46,arm,armenian,shareholder,beneficial_owner,1,1,3,0,1,0,[Սասուն Ավետիսյան],[sasoun avetisyan],[arm],"[arm_company_9a57c956e9433566, arm_company_2bd...","[arm_rec_afb758237f1b6d8e2e6fe205481fedd8, arm..."
17,entity_00003636,qentvorf venchrs inq,44,arm,armenian,shareholder,beneficial_owner,1,1,1,0,1,0,[ՔենթՎորֆ Վենչրս Ինք․],[qentvorf venchrs inq],[arm],[arm_company_0689c6b1adc0ccce],"[arm_rec_e4d4d88d83399fa0cdcbf35be35b6a89, arm..."
18,entity_00002004,global gold qorporeyshn,43,arm,armenian,shareholder,beneficial_owner,1,1,2,0,1,0,[ԳԼՈԲԱԼ ԳՈԼԴ ՔՈՐՓՈՐԵՅՇՆ],[global gold qorporeyshn],[arm],"[arm_company_384750200fe9802a, arm_company_180...","[arm_rec_90f40dc9e1cb77936a6e1e32c212611b, arm..."
19,entity_00001144,brenton kommers limited,43,arm,armenian,shareholder,beneficial_owner,1,1,1,0,1,0,[Բրենտոն Կոմմերս Լիմիտեդ],[brenton kommers limited],[arm],[arm_company_0689c6b1adc0ccce],"[arm_rec_ac59ecc60f36218a8fd49dfc53344a94, arm..."

In [7]:
# ============================================================
# FINAL SUMMARY
# ============================================================

summary = {
    "input_records": len(deduplicated_export),
    "unique_entities": canonical_export["entity_id"].nunique(),
    "singleton_entities": int((canonical_export["cluster_size"] == 1).sum()),
    "non_singleton_entities": int((canonical_export["cluster_size"] > 1).sum()),
    "records_in_duplicate_clusters": int(
        canonical_export.loc[
            canonical_export["cluster_size"] > 1,
            "cluster_size",
        ].sum()
    ),
    "largest_cluster_size": int(canonical_export["cluster_size"].max()),
    "deduplication_compression": float(
        1 - canonical_export["entity_id"].nunique() / len(deduplicated_export)
    ),
}

summary_df = pd.DataFrame([summary])

display(summary_df)

,input_records,unique_entities,singleton_entities,non_singleton_entities,records_in_duplicate_clusters,largest_cluster_size,deduplication_compression
0,89133,75690,69737,5953,19396,369,0.15082

In [8]:
# ============================================================
# SAVE FINAL FILES
# ============================================================

deduplicated_parquet_path = OUTPUT_DIR / "deduplicated_records.parquet"
deduplicated_csv_path = OUTPUT_DIR / "deduplicated_records.csv"

canonical_parquet_path = OUTPUT_DIR / "canonical_entities.parquet"
canonical_csv_path = OUTPUT_DIR / "canonical_entities.csv"

cluster_distribution_path = OUTPUT_DIR / "cluster_distribution.csv"
summary_path = OUTPUT_DIR / "final_summary.csv"

deduplicated_export.to_parquet(
    deduplicated_parquet_path,
    index=False,
)

deduplicated_export.to_csv(
    deduplicated_csv_path,
    index=False,
    encoding="utf-8-sig",
)

canonical_export.to_parquet(
    canonical_parquet_path,
    index=False,
)

canonical_export.to_csv(
    canonical_csv_path,
    index=False,
    encoding="utf-8-sig",
)

cluster_distribution.to_csv(
    cluster_distribution_path,
    index=False,
    encoding="utf-8-sig",
)

summary_df.to_csv(
    summary_path,
    index=False,
    encoding="utf-8-sig",
)

print("Saved final files:")
print(deduplicated_parquet_path)
print(deduplicated_csv_path)
print(canonical_parquet_path)
print(canonical_csv_path)
print(cluster_distribution_path)
print(summary_path)

Saved final files:
..\data\final\deduplicated_records.parquet
..\data\final\deduplicated_records.csv
..\data\final\canonical_entities.parquet
..\data\final\canonical_entities.csv
..\data\final\cluster_distribution.csv
..\data\final\final_summary.csv

In [9]:
# ============================================================
# SANITY CHECK
# ============================================================

assert len(deduplicated_export) == summary["input_records"]
assert canonical_export["entity_id"].nunique() == summary["unique_entities"]
assert deduplicated_export["entity_id"].isna().sum() == 0

print("Sanity check passed.")

Sanity check passed.

## Вывод по финальным файлам

На этом этапе были сформированы итоговые файлы для передачи заказчику.

Сформированы:

1. `deduplicated_records.parquet` / `deduplicated_records.csv`  
   Исходные записи с назначенным `entity_id`.

2. `canonical_entities.parquet` / `canonical_entities.csv`  
   Таблица уникальных сущностей.

3. `cluster_distribution.csv`  
   Распределение размеров кластеров.

4. `final_summary.csv`  
   Краткая статистика результата дедупликации.

Все записи с одинаковым `entity_id` считаются дубликатами одной сущности.